name: Check markdown links

on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # every sunday at 12:00
    - cron: "00 12 * * 0"  # https://crontab.guru/#00_12_*_*_0

jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Checker
        id: lychee
        uses: lycheeverse/lychee-action@v1.6.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          args: README.md
         
      - name: Create Issue From File
        if: env.lychee_exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[Bot] Broken Links Report"
          content-filepath: ./lychee/out.md
          labels: report
