on:
  repository_dispatch:
  workflow_dispatch:
  schedule:
    # every sunday at 12:00
    - cron: "00 12 * * 0"  # https://crontab.guru/#00_12_*_*_0
name: Check markdown links
jobs:
  linkChecker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Link Checker
        id: lychee
        # temporary workaround
        uses: InCogNiTo124/lychee-action@77af99d60df40f14642684200f8c1e9af39b71ab
        with:
          args: README.md
         
      - name: Create Issue From File
        if: steps.lychee.outputs.exit_code != 0
        uses: peter-evans/create-issue-from-file@v4
        with:
          title: "[Bot] Broken Links Report"
          content-filepath: ./lychee/out.md
          labels: report
